---
abstract: 'Test for the structure of a package'
author:
  - 'notbenh <notbenh@cpan.org>'
build_requires:
  PPI: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Structure
provides:
  Test::Structure:
    file: lib/Test/Structure.pm
    version: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
